version: "3.9"
services:
  centrifugo:
    container_name: centrifugo
    image: centrifugo/centrifugo:v6
    volumes:
      - ./config/config.json:/centrifugo/config.json
    command: centrifugo -c config.json
    ports:
      - 8008:8000
    ulimits:
      nofile:
        soft: 65535
        hard: 65535